<?php
/**
 * @category   PSystem
 * @package    PSystem_AjaxQuickCart
 * @author     Pascal System <info@pascalsystem.pl>
 * @version    1.0.2
 */
?>
<?php
/**
 * Shopping layer cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<div class="carlist">
    <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
        <fieldset>
            <table cellpadding="0" cellspacing="0" border="0" width="100%">
                <tr class="gray" height="30">
            <td>Product</td>
            <td>Qty</td>
            <td>Price</td>
         </tr>
                <?php foreach($this->getItems() as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach ?>
                </tbody>
                <tr>
            <td colspan="3">
             <?php echo $this->getChildHtml('totals'); ?>
             <span class="fl">Shipping & Handling</span>	<span class="fr pink">FREE</span>
           
            </td>
         </tr>
         <tr class="pink"  height="40">
            <td colspan="3"><a href="<?php echo $this->getUrl('checkout/cart/index') ?>"><span><span><?php echo $this->__('Process to checkout') ?></a></button>
                        </td>
                    </tr>
            </table>
            <script type="text/javascript">decorateTable('shopping-cart-table')</script>
        </fieldset>
    </form>
</div>
