<?php $_orders = $this->getOrders(); ?>
<div class="main">
    <h3><p class="text-center order_c_h">订单中心</p></h3>
    <?php if($_orders->getSize()): ?>
    <table class="table order_center_list">
        <thead></thead>
        <tbody>
        <?php foreach ($_orders as $_order): ?>
        <tr class="order_list">
            <td class="col-md-1 hidden-xs"></td>
            <td class="col-md-2 hidden-xs"><img src="<?php echo $this->getSkinUrl('') ?>v1/images/OC_goods.png"></td>
            <td class="col-md-2 visible-xs"><img src="<?php echo $this->getSkinUrl('') ?>v1/images/OC_goods1.png"></td>
            <td class="col-md-1 hidden-xs"></td>
            <td class="order_cen_content">
                <div class="pro_info">
                    <p class="pro_name">
                        <span>双子座&amp; 狮子座星爱盒</span>
                        <b>数量1,<em>&nbsp;&nbsp;<?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></em> 定制</b>
                    </p>
                    <span class="payCslice"></span>
                </div>
                <div class="pro_action">
                    <em><i class="totalPrice"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></i>元</em>

                    <img class="towardtoright" src="<?php echo $this->getSkinUrl('') ?>v1/images/arrownew.png">
                    <p class="order_state"><?php echo $_order->getStatusLabel() ?></em></p>
                </div>
                <div class="order_control">

                    <a class="radius_button ord_btn2" id="paynow" href="ord_btn2"><img src="<?php echo $this->getSkinUrl('') ?>v1/images/bluearrow.png"><span>立即支付</span></a>

                    <a class="radius_button ord_btn1" id="cancel" href="ord_btn1"><img src="<?php echo $this->getSkinUrl('') ?>v1/images/arrow.png"><span>取消订单</span></a>
                </div>
            </td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?php else: ?>
        <div style="height:130px;">
            <p><?php echo $this->__('You have placed no orders.'); ?></p>
        </div>
    <?php endif ?>
</div>