<div class="main">
    <div class="payorder_content row">

        <h3 class="page_titile">未达成态</h3>
        <div class="order_detail col-md-7 col-md-offset-3">
            <div class="time_content">
                <div class="indicator"></div>
                <ul class="step step1">
                    <li>定制包装</li>
                    <li class="goods_detail"><img src="<?php echo $this->getSkinUrl('') ?>v1/images/detail_goods.png"><b class="words">Just For U</b></li>
                    <li class="print">马上付款将于2014-9-28前印刷包</li>
                </ul>

                <ul class="step step2">
                    <li class="waitting_pay"><img class="time_point" src="<?php echo $this->getSkinUrl('') ?>v1/images/time_point.png">未支付，请尽快支付</li>
                    <li><i class="price_d">$199</i><a id="paynow" class="view_order_pay" href="/m/checkout/onepage"><img src="<?php echo $this->getSkinUrl('') ?>v1/images/arrow.png"><span>立即支付</span></a></li>
                </ul>

                <ul class="step step3">
                    <li><img class="time_point" src="<?php echo $this->getSkinUrl('') ?>v1/images/time_point.png">定制包装印刷</li>
                    <li></li>
                    <li class="goods_detail">
                        <img src="<?php echo $this->getSkinUrl('') ?>v1/images/detail_goods.png">
                        <div class="ipt pull-right timelineinput timelinegoodsinput">
                            <input type="text">
                        </div>
                        <a class="view_order_pay pull-right"><img src="<?php echo $this->getSkinUrl('') ?>v1/images/arrow.png"><span>更新文字</span></a>
                    </li>
                    <li style="padding-top:10px"><img class="time_point" src="<?php echo $this->getSkinUrl('') ?>v1/images/time_point.png">顺丰速递派送</li>
                    <li><label>收件人姓名</label><div id="name0">
                            <div class="ipt pull-right timelineinput">
                                <input type="text">
                            </div>
                            <i></i>
                            <p class="form_errMsg"></p>
                        </div></li>
                    <li><label>手机号码</label>
                        <div class="ipt  pull-right timelineinput">
                            <input type="text">
                        </div>
                        <i></i>
                        <p class="form_errMsg"></p>
                    </li>
                    <li><label>邮寄地址</label>
                        <div class="txt  pull-right">
                            <textarea class="timelineinput"></textarea>
                        </div>
                        <i></i>
                        <p class="form_errMsg"></p>
                    </li>
                    <li><a id="update_add" class="view_order_pay pull-right"><img src="<?php echo $this->getSkinUrl('') ?>v1/images/arrow.png"><span>更新地址</span></a></li>
                    <li><img class="time_point" src="<?php echo $this->getSkinUrl('') ?>v1/images/time_point.png">签收完成</li>
                </ul>

                <ul class="step step4">
                    <li><img class="time_point" src="<?php echo $this->getSkinUrl('') ?>v1/images/time_point.png">成功支付:   2014-9-15 , 13:20</li>
                    <li>定制包装印刷</li>
                    <li class="goods_detail"><img src="<?php echo $this->getSkinUrl('') ?>v1/images/detail_goods.png"><b class="words">Just For U</b></li>
                    <li class="print">将于 2014-9-15前包装完毕</li>
                    <li>顺丰速递派送</li>
                    <li><label>收件人姓名：</label>xxxx</li>
                    <li><label>手机号码：</label>xxxx</li>
                    <li><label>邮寄地址：</label>xxxx</li>
                    <li class="print">将于 2014-9-15北京朝阳区转出</li>
                    <li class="print">将于 2014-9-15北京朝阳区转出</li>
                </ul>

                <ul class="step step5">
                    <li><img class="time_point" src="<?php echo $this->getSkinUrl('') ?>v1/images/time_point.png">签收完成</li>
                    <li class="print">将于 2014-9-15签收人是：dd</li>
                </ul>

            </div>
        </div>
    </div>

</div>