<div id="wrapper" class='wrapper'>
    <div class="main shopingbag">
        <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
            <table class="table order_center_list">
                <thead><h3><p class="text-center order_c_h">订单中心</p></h3></thead>
                <tbody>
                <?php $index = 0; foreach($this->getItems() as $_item): ?>
                    <?php $index = $index + 1; if($index > 1):?>
                    <?php else :?>
                    <?php echo $this->getItemHtml($_item) ?>
                    <?php endif ?>
                <?php endforeach ?>
                </tbody>
            </table>
        </form>
    </div>
</div>