<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?> 
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?> 
</div>

<div id="blog" class="blog row">
<img src="<?php echo $this->getUrl('') ?>media/wysiwyg/blog/durex-blog.jpg" alt="" style="padding-bottom:30px" />

            <div class="menu-categories col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <ul>
                    <?php $cats = $this->getCategories(); ?>
                    <?php foreach ($cats as $cat): ?>
                        <li><a href="<?php echo $cat->getAddress(); ?>" ><?php echo $cat->getTitle(); ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>	

 <?php $count=0;?>
<?php foreach ($posts as $post): ?>
    <?php $count++;?>
  <?php if($count==1): ?>
   <div class="box5 col-lg-6 col-md-6 col-sm-6 col-xs-12">
    <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12"><a class="box4 pink2" href="<?php echo $post->getAddress(); ?>" ><div class="topTitle"><?php echo $post->getTitle(); ?></div><p><?php echo $post->getPostContentForList(); ?></p></a></div>
   <?php endif; ?> 
    <?php if($count==2): ?> 
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12"><a class="box4 pink2 nomr" href="<?php echo $post->getAddress(); ?>" ><p><?php echo $post->getPostContentForList(); ?></p><div class="topTitle" style="position:absolute; bottom:0;"><?php echo $post->getTitle(); ?></div></a></div>
   <?php endif; ?> 
    <?php if($count==3): ?> 
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><a class="box3 clear pink2 nomr" href="<?php echo $post->getAddress(); ?>" ><div class="topTitle"><?php echo $post->getTitle(); ?></div><p><?php echo $post->getPostContentForList(); ?></p></a></div>
    </div>
    </div>
 <?php endif; ?>
 <?php if($count<8 && $count>=4): ?>  
 <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12"><a class=" box2 black  bg6 <?php if($count==5): ?>nomr<?php endif; ?>" href="<?php echo $post->getAddress(); ?>"   style="background-image:url(<?php echo $this->getUrl('')."media/".$post->getPostImg(); ?>)"><div class="title"><?php echo $post->getTitle(); ?></div></a></div>
 <?php endif; ?>
 <?php if($count==8): ?>  
 <div class=" col-lg-6 col-md-6 col-sm-6 col-xs-12"><a class="box1 black bg5 nomr" href="<?php echo $post->getAddress(); ?>"  style="background-image:url(<?php echo $this->getUrl('')."media/".$post->getPostImg(); ?>)"><div class="title"><?php echo $post->getTitle(); ?></div></a></div>
 <?php endif; ?>
 
    
<?php endforeach; ?> 
</div>
 <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<?php $this->getPages(); ?>


<!--div class="postWrapper">
        <div class="postTitle">
            <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
            <h3><?php echo $post->getCreatedTime(); ?></h3>
        </div>
        <div class="postContent"><?php echo $post->getPostContent(); ?></div>

        <?php echo $this->getBookmarkHtml($post) ?>
        <div class="tags"><?php echo $this->getTagsHtml($post) ?></div>
        <div class="postDetails">
            <?php if ($this->getCommentsEnabled()): ?>
                <?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" >Comments</a> | 
            <?php endif; ?>
            <?php $postCats = $post->getCats(); ?>
            <?php if (!empty($postCats)): ?>
                <?php echo Mage::helper('blog')->__('Posted in'); ?>
                <?php foreach ($postCats as $data): ?>               
                    <a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a> 
                <?php endforeach; ?> 
            <?php else: ?>
                <?php echo Mage::helper('blog')->__('Posted'); ?>
            <?php endif; ?><?php echo $this->__("By"); ?> <?php echo $post->getUser(); ?></div>
    </div  -->