 <?php $posts = $this->getPosts(); ?>

 <div id="blog" class="blog">
<img src="<?php echo $this->getUrl('') ?>media/wysiwyg/blog/durex-blog.jpg" alt="" style="padding-bottom:30px" />
<?php if (count($posts)): ?>
 <?php $count=0;?>
<?php foreach ($posts as $post): ?>
    <?php $count++;?>
  <?php if($count==1): ?>
   <div class="box5 fl">
    <a class="box4 fl pink2" href="<?php echo $post->getAddress(); ?>" ><div class="topTitle"><?php echo $post->getTitle(); ?></div><p><?php echo $post->getPostContentForList(); ?></p></a>
   <?php endif; ?> 
    <?php if($count==2): ?> 
    <a class="box4 fl pink2 nomr" href="<?php echo $post->getAddress(); ?>" ><div class="topTitle"><?php echo $post->getTitle(); ?></div><p><?php echo $post->getPostContentForList(); ?></p></a>
   <?php endif; ?> 
    <?php if($count==3): ?> 
    <a class="box3 clear pink2 nomr" href="<?php echo $post->getAddress(); ?>" ><div class="topTitle"><?php echo $post->getTitle(); ?></div><p><?php echo $post->getPostContentForList(); ?></p></a>
    </div>
 <?php endif; ?>
 <?php if($count<8 && $count>=4): ?>  
 <a class="box2 fl black  bg6 <?php if($count==5): ?>nomr<?php endif; ?>" href="<?php echo $post->getAddress(); ?>"   style="background-image:url(<?php echo $this->getUrl('')."media/".$post->getPostImg(); ?>)"><div class="title"><?php echo $post->getTitle(); ?></div><p><?php echo $post->getPostContentForList(); ?></p></a>
 <?php endif; ?>
 <?php if($count==8): ?>  
 <a class="box1 fl black bg5 nomr" href="<?php echo $post->getAddress(); ?>"  style="background-image:url(<?php echo $this->getUrl('')."media/".$post->getPostImg(); ?>)"><div class="divBottom"><div class="title"><?php echo $post->getTitle(); ?></div><p><?php echo $post->getPostContentForList(); ?></p></div></a>
 <?php endif; ?>
 
    
<?php endforeach; ?> 
</div>
 <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<?php else: ?>  
    <?php echo Mage::helper('blog')->__('No Posts in this Category.'); ?>
<?php endif; ?>
